lists/urls.py
from django.urls import path
from lists import views

app_name='lists'

urlpatterns=[ 
 path('', views.index, name='index'),
 path('todolist/add', views.addTodolist, name='add_todolist'),
 path('todolist/details/<int:todolist_id>',views.details,name='details'),
 path('todolist/addtodo/<int:todolist_id>', views.addTodo,name='add_todo'),
 path('todolist/deletetodo/<int:todolist_id>', views.deleteTodo, name='delete_todo'),
path('todolist/deletetodolist/<int:todolist_id>' , views.deleteTodolist, name='delete_todolist') 
]

mytodolist/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include('lists.urls')),
    path('admin/', admin.site.urls),
]

lists/models.py
from django.db import models

# Create your models here.
class Todolist(models.Model):
	title=models.CharField(max_length=150)
	created_at=models.DateField(auto_now_add=True)

	def __str__(self):
		return self.title



class Todo(models.Model):
	todolist=models.ForeignKey(Todolist,on_delete=models.CASCADE)
	title=models.CharField(max_length=150)
	description=models.CharField(max_length=450)
	
	def __str__(self):
		return self.title

lists/forms.py
from django import forms

class Todoform(forms.Form):
	title=forms.CharField(widget=forms.TextInput(attrs={'placeholder':"enter a title"}))
 
class TodoListingForm(forms.Form):
	todo_name=forms.CharField(widget=forms.TextInput(attrs={'placeholder':"enter work name"}))
	todo_description=forms.CharField(widget=forms.Textarea())

lists/views.py
from django.shortcuts import render, redirect, get_object_or_404

from lists.models import Todolist,Todo
from lists.forms import Todoform, TodoListingForm
from django.http import HttpResponse

def index(request):
	print(request.user.is_authenticated)
	return render(request,'lists/index.html', { 'Todoform': Todoform() , 'Todolist' : Todolist.objects.all() })
  

def addTodolist(request):
	if request.method =="POST":
		form=Todoform(request.POST)
		if form.is_valid():
			print(request.POST['title'])
			newTodoList=Todolist( title= request.POST['title'])
			newTodoList.save()
			print(newTodoList)
			for todo in Todolist.objects.all():
				print(todo)
	return redirect('lists:index')

def details(request,todolist_id):
	todolist=get_object_or_404(Todolist,pk=todolist_id)
	return render(request,'lists/details.html',{'todolist': todolist, 'form': TodoListingForm()})


def addTodo(request, todolist_id):
	todolist=get_object_or_404(Todolist,pk=todolist_id)
	print(todolist)
	if request.method=="POST":
		form=TodoListingForm(request.POST)
		if form.is_valid():
			newTodo=Todo(todolist=todolist,title=request.POST['todo_name'],description=request.POST['todo_description'])
			newTodo.save()
	return redirect( 'lists:details', todolist_id=todolist_id )

def deleteTodo(request, todolist_id):
	if request.method== 'POST':	
		Todo.objects.filter(pk=request.POST['xname']).delete()
	return redirect('lists:details', todolist_id=todolist_id)

def deleteTodolist(request,todolist_id):
	if request.method=="POST":
		Todolist.objects.filter(pk=todolist_id).delete()
	return redirect('lists:index')

lists/templates/lists/details.html
<h1>Welcome to {{ todolist.title}} todolist</h1>

{%if todolist.todo_set.count > 0%}
<h4>list of todo to sort out</h4>
<table>
	
		<td>Todo</td>
		<td>Description</td>
	<td>delete</td>
{%for x in todolist.todo_set.all %}
 <tr>
 <td>{{x}}</td>
<td>{{x.description}}</td>
<td><form method="POST" action="{% url 'lists:delete_todo' todolist.id %}">
	{%csrf_token%}
	<input type='hidden' name='xname' value='{{x.id}}'>
	<input type="submit" value='delete'> </form>
</td>
</tr>
{%endfor%}
</table>
{%endif%}
<form method="POST" action="{% url 'lists:add_todo' todolist.id %}">
	{%csrf_token%}
	{{form}}
	<br>
	<input type="submit" value="Add todo">
</form>

lists/templates/lists/index.html
<h1>Welcome</h1>



 <h3>list of todolists</h3>
 <ul>
 	{% for todo in Todolist %}
 	<li> 
 		<a href="{% url 'lists:details' todo.id %} "> {{todo}} </a>
 		<form method='POST' action="{% url 'lists:delete_todolist'  todo.id %}">
 			{%csrf_token%}
         <input type="submit" value='delete'>
 		</form>
    </li> 	
{%endfor%}
</ul>


<form action="{% url 'lists:add_todolist'  %}" method="POST">
 {% csrf_token %}
 {{ Todoform }}
 <input type="submit" name="submit" value="Add form">
</form>